- name: install nginx
  apt: pkg=nginx state=installed

- name: remove default site
  file: path=/etc/nginx/{{ item }} state=absent
  with_items:
    - sites-available/default
    - sites-enabled/default

- name: add spotholder site
  template: src=spotholder.sandbox.j2 dest=/etc/nginx/sites-available/spotholder.sandbox.loc

- name: enable spotholder site
  file: src=/etc/nginx/sites-available/spotholder.sandbox.loc dest=/etc/nginx/sites-enabled/spotholder.sandbox.loc state=link
  notify: restart nginx
